"""
Gabriel Meran
CS 100 2016F Section 021
HW 0.2 Sept 16, 2016
"""
CS.2
>>> import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> t.forward(50)
>>> t.forward(50)
>>> t.left(100)
>>> t.left(-50)
>>> t.left(50)
>>> t.left(-10)
>>> t.forward(100)
>>> t.left(90)
>>> t.forward(100)
>>> t.left(90)
>>> t.forward(100)
>>> s.bye()
>>> 

CS.3
>>> import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> t.left(50)
>>> t.forward(100)
>>> t.left(50)
>>> t.left(10)
>>> t.forward(100)
>>> t.undo()
>>> t.left(10)
>>> t.forward(100)
>>> t.left(70)
>>> t.left(10)
>>> t.left(20)
>>> t.forward(100)
>>> t.undo()
>>> t.left(10)
>>> t.forward(100)
>>> t.left(80)
>>> t.forward(100)
>>> t.undo()
>>> t.left(-20)
>>> t.forward(100)
>>> t.undo()
>>> t.left(10)
>>> t.forward(100)
>>> s.bye()

CS.4
(Pentagon)
>> import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> t.forward(50)
>>> u = turtle.Turtle()
>>> u.right(180)
>>> u.forward(50)
>>> u.right(64)
>>> u.undo()
>>> u.right(50)
>>> u.undo()
>>> u.right(90)
>>> u.left(10)
>>> u.left(10)
>>> u.forward(100)
>>> t.left(90)
>>> t.right(20)
>>> t.forward(100)
>>> t.right(20)
>>> t.right(-20)
>>> t.left(90)
>>> u.right(90)
>>> u.left(20)
>>> t.right(20)
>>> u.forward(100)
>>> t.forward(100)
>>> u.forward(10)
>>> t.forward(10)

(Hexagon)
>>> import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> t.forward(50)
>>> u = turtle.Turtle()
>>> u.right(180)
>>> u.forward(50)
>>> u.left(60)
>>> u.undo()
>>> u.right(60)
>>> t.left(60)
>>> u.forward(100)
>>> t.forward(100)
>>> u.right(60)
>>> t.left(60)
>>> l.forward(100)
>>> t.forward(100)
>>> u.forward(100)
>>> u.right(30)
>>> u.right(30)
>>> t.left(60)
>>> u.forward(50)
>>> t.forward(50)

(Heptagon)
>>> import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> t.forward(50)
>>> u = turtle.Turtle()
>>> u.right(180)
>>> u.forward(50)
>>> u.right(50)
>>> t.left(50)
>>> t.forward(100)
>>> u.forward(100)
>>> u.right(50)
>>> t.left(50)
>>> t.forward(100)
>>> u.forward(100)
>>> u.right(60)
>>> t.left(60)
>>> u.forward(100)
>>> t.forward(100)
>>> t.forward(5)
>>> u.forward(5)

(Octagon)
>>> import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> t.forward(50)
>>> u = turtle.Turtle()
>>> u.right(180)
>>> u.forward(50)
>>> t.left(40)
>>> u.right(40)
>>> t.forward(100)
>>> u.forward(100)
>>> u.right(50)
>>> t.left(50)
>>> u.forward(100)
>>> t.forward(100)
>>> u.right(40)
>>> t.left(40)
>>> u.forward(100)
>>> t.forward(100)
>>> u.right(50)
>>> t.left(50)
>>> t.forward(50)
>>> u.forward(50)
>>> u.forward(10)
>>> t.forward(10)
>>> u.forward(5)
>>> s.bye()

CS.6
import turtle
>>> s = turtle.Screen()
>>> t = turtle.Turtle()
>>> x = -100
>>> y = 100
>>> t.penup()
>>> t.goto(x,y)
>>> t.pendown()
>>> t.circle(100)
>>> t.penup()
>>> x = 0
>>> y =0
>>> t.goto(x,y)
>>> t.pendown()
>>> t.circle(100)
>>> t.penup()
>>> x = -90
>>> y = -90
>>> t.goto(x,y)
>>> t.circle(100)
>>> t.pendown()
>>> t.circle(100)
>>> t.penup()
>>> x = -160
>>> y = 10
>>> t.goto(x,y)
>>> t.pendown()
>>> t.circle(100)
>>> s.bye()
